security:
  user:
    name: admin
    password: 123456
mybatis:
  mapper-locations: classpath*:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
