/* 用户列表 */
DROP TABLE IF EXISTS `TB_SECURITY2_USER`;
CREATE TABLE `TB_SECURITY2_USER`(
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `username` VARCHAR(256) NOT NULL COMMENT '用户名',
  `password` VARCHAR(256) NOT NULL COMMENT '密码',
  `createTime` BIGINT(20) DEFAULT 0 NOT NULL COMMENT '创建时间',
  `updateTime` BIGINT(20) DEFAULT 0 NOT NULL COMMENT '更新时间',
  `enabled` BOOLEAN DEFAULT TRUE NOT NULL COMMENT '是否启用',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4 COMMENT '用户列表';
